version: '3.1'

services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: server-apache2
    working_dir: /var/www/webserver
    ports:
      - 80:80
    volumes:
      - /var/machine/code/php:/var/www/webserver
      - /var/machine/logs/apache2:/var/log/apache2
      - /var/machine/config/apache2/apache2.conf:/etc/apache2/apache2.conf
      - /var/machine/config/apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
      #- /var/machine/config/apache2/sites-available/vtigersand.conf:/etc/apache2/sites-available/vtigersand.conf

    networks:
      rests_net:
        ipv4_address: 192.10.0.2
networks:
  rests_net:
    external:
      name: machinelan_rests_net
